### ISSUE TITLE
Possible error in equation 188 or 189

### ISSUE THREAD

**Issue by MReed2** [bryanwweber/orbital-mechanics-notes#11]
Equation 188 has a μ² term.
Equation 189 (and all descendant equations) have only a μ term.

The only thing that changes between 188 and 189 is solving a trivial integral -- I don't see how a 1/μ could possibly be generated by solving this integral.

The μ² term in 188 seems to be correct -- equation 187 involves squaring both sides of the equation 113 (the Orbital Equation), so the μ in this equation would logically turn into a μ².

Is this a copy and paste error?

Also, it would be helpful if the text points out that generating equation 187 requires squaring both sides of 113 in addition to "Substituting the orbit equation and separating variables."

It would also be nice to have an explanation of _why_ we need equation 186 at all (vs just using equation 185 directly).  I'm pretty sure the answer is "We need to put the right hand side of the integral into a standard form, so we can look up the integral, and the easiest way to do this is to square both sides of the equation" but making this explicit wouldn't hurt.  I mean, equation 185 already expresses dν/dt in terms of r, so why not substitute it directly into 113 and skip 186 altogether?

Finally, it would be helpful if the final form of equation 186 was "h*dt/dν = r²", as that is the form that it is used in equation 187.

**Comment by MReed2** [comment]
Oh, the μ² comes back in equation 195, so I'm fairly confident in saying that equation 189 (and descendant equations) are incorrect due to a copy and paste error.

Not confident enough to change the text, though. :)

**Comment by bryanwweber** [comment]
Please feel free to make the edit, it's easier for me to check it with the context and the proposed change. It won't get published to the website until it's reviewed and merged, so no worries if we have to make more edits 😄

**Comment by bryanwweber** [comment]
@MReed2 Does the text change in #14 help with why the substitution is done this way? Thanks for pointing out the typo!

**Comment by MReed2** [comment]
Yes, I think that addresses my concern.  Thanks for your time.
