### ISSUE TITLE
GitHub repository isn't linked to from the webpage

### ISSUE THREAD

**Issue by MReed2** [bryanwweber/orbital-mechanics-notes#9]
Yeah, finding this repository was...  Difficult.

Thankfully, a github search for your e-mail address returns a few issues that you've opened on other projects, and from there I could find your page, and from there it was straightforward to find this repository.

But there is no reference to GitHub on any of the pages but the introduction, and that page doesn't include a link.  I even checked the webpage source -- no matches for "github" were found.

This is a good way to reduce the number of bugs reported in your webpage, admittedly. :)

**Comment by MReed2** [comment]
It wasn't my intention to be hostile in the slightest -- as you suspected, I was trying for humor, and obviously failed.

This is a great resource, and I'm deeply impressed by the amount of time and effort it must have been to put it together.  I'm actually in the process (slowly) of trying to strip this down to put together a guide for laypeople for certain games that both involve programming and orbital mechanics.  I'm not sure how successful the effort is going to be, but its an interesting project.

**Comment by bryanwweber** [comment]
Thanks for the kind words! And for taking my message in the spirit I intended as well. I truly appreciate getting feedback on the text, etc. I'd be more than happy to look at pull requests for either of the other two issues you created, if you want to try editing the text 😄

**Comment by MReed2** [comment]
I don't feel qualified to edit the equations.  You are a retired professor, and I'm someone who took two semesters of college physics a _long_ time ago.

I might take a look at fixing the other two issues via pull requests as I am qualified to fix those.

**Comment by bryanwweber** [comment]
Heh, retired to private industry indeed 😄 If you can identify the issue in the equation, you're qualified to fix it. You may not know the answer, which is fine (and which I sincerely doubt), but that doesn't address the qualifications 😸
